name: 'Hello World'
description: 'Greet someone'
inputs:
  status-types:  # id of input
    description: 'The tasks check if the result is success/failure'
    required: true
    default: 'label' 
    type: choice
    options:
      - label
      - context-string
      - label/context-string
  github-token:
    description: 'The auth token'
    required: true
  success-label-status:
    description: 'The label status result on success tasks validation'
    required: false
    default: 'tasks-complete'
  failure-label-status:
    description: 'The label status result on failure tasks validation'
    required: false
    default: 'tasks-incomplete'
  context-string-status:
    description: 'The context-string status'
    required: false
    default: 'tasks-validation'


outputs:
  tasks-complete:
    description: "Return if tasks are complete"
runs:
  using: 'node16'
  main: 'dist/index.js'