name: Verify action

on:
  pull_request_target:
    types: [description]
  pull_request:
    types: [edited]

jobs:
  tasks-verification-job:
    runs-on: ubuntu-latest
    name: Job to verify PR tasks completion
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: tasks verification action step
        id: tasks-verified
        uses: ./ 
        with: 
          status-types: 'label/context-string'
          github-token: ${{ secrets.AUTH_TOKEN }}
      - name: get output
        run: echo "The tasks is complete = ${{ steps.tasks-verified.outputs.tasks-complete }}"
